version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none

  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - dupl
    - goconst
    - mnd
    - lll
    - revive
    - gocritic
    - prealloc
    - testifylint
    - gosec
    - cyclop
    - misspell
    - nilerr
    - godot
    - testpackage
    - thelper
    - tparallel
    - depguard

  settings:
    govet:
      enable:
        - shadow

    gocritic:
      enabled-tags:
        - performance
        - style
        - diagnostic

    cyclop:
      max-complexity: 10

    misspell:
      locale: US

    gosec:
      severity: medium
      confidence: medium

    gci:
      sections:
        - standard
        - default
        - prefix(go.trai.ch/same)

    godot:
      scope: toplevel
      exclude:
        - "^(?i)todo:"
        - "^(?i)fixme:"
      period: true

    testifylint:
      enable-all: true

    mnd:
      ignored-numbers:
        - "0"
        - "1"
        - "2"
    depguard:
      rules:
        core:
          list-mode: strict
          files:
            - "**/internal/core/**/*.go"
          allow:
            - $gostd
            - "go.trai.ch/same/internal/core"
            - "go.trai.ch/zerr"
            - "github.com/stretchr/testify"

        engine:
          list-mode: lax
          files:
            - "**/internal/engine/**/*.go"
          deny:
            - pkg: "go.trai.ch/same/internal/adapters"
              desc: "engine must not depend on adapters (infra layer)"
            - pkg: "go.trai.ch/same/internal/app"
              desc: "engine must not depend on app layer"
            - pkg: "go.trai.ch/same/cmd"
              desc: "engine must not depend on cmd"

        adapters:
          list-mode: lax
          files:
            - "**/internal/adapters/**/*.go"
          deny:
            - pkg: "go.trai.ch/same/internal/engine"
              desc: "adapters must not depend on engine"
            - pkg: "go.trai.ch/same/internal/app"
              desc: "adapters must not depend on app"

        app:
          list-mode: lax
          files:
            - "**/internal/app/**/*.go"
          deny:
            - pkg: "go.trai.ch/same/internal/adapters"
              desc: "app should depend on ports, not concrete adapters"
            - pkg: "go.trai.ch/same/cmd"
              desc: "app must not depend on cmd"

        cmd:
          list-mode: lax
          files:
            - "**/cmd/**/*.go"
          deny:
            - pkg: "go.trai.ch/same/internal/adapters"
              desc: "CLI should go through app layer, not adapters directly"
            # Note: internal/wiring is allowed to be imported by cmd to trigger side-effects.

formatters:
  enable:
    - gofumpt
    - gci
