codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  range: 60...80
  round: down
  precision: 2

  status:
    project:
      default:
        target: auto 
        threshold: 1%
    patch:
      default:
        target: 80% 
        threshold: 1%

ignore:
    - "**/*_test.go"
    - "**/mocks/**"
    - "**/mock_*.go"
    - "**/*_mock.go"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
