// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/daemon/v1/daemon.proto

package daemonv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// idle_remaining_seconds is the time remaining before auto-shutdown.
	IdleRemainingSeconds int64 `protobuf:"varint,1,opt,name=idle_remaining_seconds,json=idleRemainingSeconds,proto3" json:"idle_remaining_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetIdleRemainingSeconds() int64 {
	if x != nil {
		return x.IdleRemainingSeconds
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{2}
}

type StatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Running              bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Pid                  int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	UptimeSeconds        int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	LastActivityUnix     int64                  `protobuf:"varint,4,opt,name=last_activity_unix,json=lastActivityUnix,proto3" json:"last_activity_unix,omitempty"`
	IdleRemainingSeconds int64                  `protobuf:"varint,5,opt,name=idle_remaining_seconds,json=idleRemainingSeconds,proto3" json:"idle_remaining_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetLastActivityUnix() int64 {
	if x != nil {
		return x.LastActivityUnix
	}
	return 0
}

func (x *StatusResponse) GetIdleRemainingSeconds() int64 {
	if x != nil {
		return x.IdleRemainingSeconds
	}
	return 0
}

type ShutdownRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// graceful indicates whether to wait for in-flight operations.
	Graceful      bool `protobuf:"varint,1,opt,name=graceful,proto3" json:"graceful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *ShutdownRequest) GetGraceful() bool {
	if x != nil {
		return x.Graceful
	}
	return false
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *ShutdownResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_daemon_v1_daemon_proto protoreflect.FileDescriptor

const file_api_daemon_v1_daemon_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/daemon/v1/daemon.proto\x12\tdaemon.v1\"\r\n" +
	"\vPingRequest\"D\n" +
	"\fPingResponse\x124\n" +
	"\x16idle_remaining_seconds\x18\x01 \x01(\x03R\x14idleRemainingSeconds\"\x0f\n" +
	"\rStatusRequest\"\xc7\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12,\n" +
	"\x12last_activity_unix\x18\x04 \x01(\x03R\x10lastActivityUnix\x124\n" +
	"\x16idle_remaining_seconds\x18\x05 \x01(\x03R\x14idleRemainingSeconds\"-\n" +
	"\x0fShutdownRequest\x12\x1a\n" +
	"\bgraceful\x18\x01 \x01(\bR\bgraceful\",\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcc\x01\n" +
	"\rDaemonService\x127\n" +
	"\x04Ping\x12\x16.daemon.v1.PingRequest\x1a\x17.daemon.v1.PingResponse\x12=\n" +
	"\x06Status\x12\x18.daemon.v1.StatusRequest\x1a\x19.daemon.v1.StatusResponse\x12C\n" +
	"\bShutdown\x12\x1a.daemon.v1.ShutdownRequest\x1a\x1b.daemon.v1.ShutdownResponseB(Z&go.trai.ch/same/api/daemon/v1;daemonv1b\x06proto3"

var (
	file_api_daemon_v1_daemon_proto_rawDescOnce sync.Once
	file_api_daemon_v1_daemon_proto_rawDescData []byte
)

func file_api_daemon_v1_daemon_proto_rawDescGZIP() []byte {
	file_api_daemon_v1_daemon_proto_rawDescOnce.Do(func() {
		file_api_daemon_v1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_daemon_v1_daemon_proto_rawDesc), len(file_api_daemon_v1_daemon_proto_rawDesc)))
	})
	return file_api_daemon_v1_daemon_proto_rawDescData
}

var file_api_daemon_v1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_daemon_v1_daemon_proto_goTypes = []any{
	(*PingRequest)(nil),      // 0: daemon.v1.PingRequest
	(*PingResponse)(nil),     // 1: daemon.v1.PingResponse
	(*StatusRequest)(nil),    // 2: daemon.v1.StatusRequest
	(*StatusResponse)(nil),   // 3: daemon.v1.StatusResponse
	(*ShutdownRequest)(nil),  // 4: daemon.v1.ShutdownRequest
	(*ShutdownResponse)(nil), // 5: daemon.v1.ShutdownResponse
}
var file_api_daemon_v1_daemon_proto_depIdxs = []int32{
	0, // 0: daemon.v1.DaemonService.Ping:input_type -> daemon.v1.PingRequest
	2, // 1: daemon.v1.DaemonService.Status:input_type -> daemon.v1.StatusRequest
	4, // 2: daemon.v1.DaemonService.Shutdown:input_type -> daemon.v1.ShutdownRequest
	1, // 3: daemon.v1.DaemonService.Ping:output_type -> daemon.v1.PingResponse
	3, // 4: daemon.v1.DaemonService.Status:output_type -> daemon.v1.StatusResponse
	5, // 5: daemon.v1.DaemonService.Shutdown:output_type -> daemon.v1.ShutdownResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_daemon_v1_daemon_proto_init() }
func file_api_daemon_v1_daemon_proto_init() {
	if File_api_daemon_v1_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_daemon_v1_daemon_proto_rawDesc), len(file_api_daemon_v1_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_daemon_v1_daemon_proto_goTypes,
		DependencyIndexes: file_api_daemon_v1_daemon_proto_depIdxs,
		MessageInfos:      file_api_daemon_v1_daemon_proto_msgTypes,
	}.Build()
	File_api_daemon_v1_daemon_proto = out.File
	file_api_daemon_v1_daemon_proto_goTypes = nil
	file_api_daemon_v1_daemon_proto_depIdxs = nil
}
