// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/daemon/v1/daemon.proto

package daemonv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInputHashResponse_State int32

const (
	GetInputHashResponse_READY   GetInputHashResponse_State = 0
	GetInputHashResponse_PENDING GetInputHashResponse_State = 1
	GetInputHashResponse_UNKNOWN GetInputHashResponse_State = 2
)

// Enum value maps for GetInputHashResponse_State.
var (
	GetInputHashResponse_State_name = map[int32]string{
		0: "READY",
		1: "PENDING",
		2: "UNKNOWN",
	}
	GetInputHashResponse_State_value = map[string]int32{
		"READY":   0,
		"PENDING": 1,
		"UNKNOWN": 2,
	}
)

func (x GetInputHashResponse_State) Enum() *GetInputHashResponse_State {
	p := new(GetInputHashResponse_State)
	*p = x
	return p
}

func (x GetInputHashResponse_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetInputHashResponse_State) Descriptor() protoreflect.EnumDescriptor {
	return file_api_daemon_v1_daemon_proto_enumTypes[0].Descriptor()
}

func (GetInputHashResponse_State) Type() protoreflect.EnumType {
	return &file_api_daemon_v1_daemon_proto_enumTypes[0]
}

func (x GetInputHashResponse_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetInputHashResponse_State.Descriptor instead.
func (GetInputHashResponse_State) EnumDescriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{13, 0}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// idle_remaining_seconds is the time remaining before auto-shutdown.
	IdleRemainingSeconds int64 `protobuf:"varint,1,opt,name=idle_remaining_seconds,json=idleRemainingSeconds,proto3" json:"idle_remaining_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetIdleRemainingSeconds() int64 {
	if x != nil {
		return x.IdleRemainingSeconds
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{2}
}

type StatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Running              bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Pid                  int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	UptimeSeconds        int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	LastActivityUnix     int64                  `protobuf:"varint,4,opt,name=last_activity_unix,json=lastActivityUnix,proto3" json:"last_activity_unix,omitempty"`
	IdleRemainingSeconds int64                  `protobuf:"varint,5,opt,name=idle_remaining_seconds,json=idleRemainingSeconds,proto3" json:"idle_remaining_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetLastActivityUnix() int64 {
	if x != nil {
		return x.LastActivityUnix
	}
	return 0
}

func (x *StatusResponse) GetIdleRemainingSeconds() int64 {
	if x != nil {
		return x.IdleRemainingSeconds
	}
	return 0
}

type ShutdownRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// graceful indicates whether to wait for in-flight operations.
	Graceful      bool `protobuf:"varint,1,opt,name=graceful,proto3" json:"graceful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *ShutdownRequest) GetGraceful() bool {
	if x != nil {
		return x.Graceful
	}
	return false
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *ShutdownResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ConfigMtime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	MtimeUnixNano int64                  `protobuf:"varint,2,opt,name=mtime_unix_nano,json=mtimeUnixNano,proto3" json:"mtime_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMtime) Reset() {
	*x = ConfigMtime{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMtime) ProtoMessage() {}

func (x *ConfigMtime) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMtime.ProtoReflect.Descriptor instead.
func (*ConfigMtime) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigMtime) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConfigMtime) GetMtimeUnixNano() int64 {
	if x != nil {
		return x.MtimeUnixNano
	}
	return 0
}

type GetGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cwd           string                 `protobuf:"bytes,1,opt,name=cwd,proto3" json:"cwd,omitempty"`
	ConfigMtimes  []*ConfigMtime         `protobuf:"bytes,2,rep,name=config_mtimes,json=configMtimes,proto3" json:"config_mtimes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphRequest) Reset() {
	*x = GetGraphRequest{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphRequest) ProtoMessage() {}

func (x *GetGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphRequest.ProtoReflect.Descriptor instead.
func (*GetGraphRequest) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *GetGraphRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *GetGraphRequest) GetConfigMtimes() []*ConfigMtime {
	if x != nil {
		return x.ConfigMtimes
	}
	return nil
}

type TaskProto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command         []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Inputs          []string               `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs         []string               `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Tools           map[string]string      `protobuf:"bytes,5,rep,name=tools,proto3" json:"tools,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Dependencies    []string               `protobuf:"bytes,6,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Environment     map[string]string      `protobuf:"bytes,7,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir      string                 `protobuf:"bytes,8,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	RebuildStrategy string                 `protobuf:"bytes,9,opt,name=rebuild_strategy,json=rebuildStrategy,proto3" json:"rebuild_strategy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskProto) Reset() {
	*x = TaskProto{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProto) ProtoMessage() {}

func (x *TaskProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProto.ProtoReflect.Descriptor instead.
func (*TaskProto) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *TaskProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskProto) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *TaskProto) GetInputs() []string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *TaskProto) GetOutputs() []string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *TaskProto) GetTools() map[string]string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *TaskProto) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *TaskProto) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *TaskProto) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *TaskProto) GetRebuildStrategy() string {
	if x != nil {
		return x.RebuildStrategy
	}
	return ""
}

type GetGraphResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CacheHit      bool                   `protobuf:"varint,1,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	Root          string                 `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	Tasks         []*TaskProto           `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphResponse) Reset() {
	*x = GetGraphResponse{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphResponse) ProtoMessage() {}

func (x *GetGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphResponse.ProtoReflect.Descriptor instead.
func (*GetGraphResponse) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *GetGraphResponse) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *GetGraphResponse) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *GetGraphResponse) GetTasks() []*TaskProto {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvId         string                 `protobuf:"bytes,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	Tools         map[string]string      `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentRequest) Reset() {
	*x = GetEnvironmentRequest{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentRequest) ProtoMessage() {}

func (x *GetEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*GetEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *GetEnvironmentRequest) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

func (x *GetEnvironmentRequest) GetTools() map[string]string {
	if x != nil {
		return x.Tools
	}
	return nil
}

type GetEnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CacheHit      bool                   `protobuf:"varint,1,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	EnvVars       []string               `protobuf:"bytes,2,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentResponse) Reset() {
	*x = GetEnvironmentResponse{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentResponse) ProtoMessage() {}

func (x *GetEnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentResponse.ProtoReflect.Descriptor instead.
func (*GetEnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *GetEnvironmentResponse) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *GetEnvironmentResponse) GetEnvVars() []string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

type GetInputHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskName      string                 `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Root          string                 `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	Environment   map[string]string      `protobuf:"bytes,3,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInputHashRequest) Reset() {
	*x = GetInputHashRequest{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInputHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInputHashRequest) ProtoMessage() {}

func (x *GetInputHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInputHashRequest.ProtoReflect.Descriptor instead.
func (*GetInputHashRequest) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *GetInputHashRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *GetInputHashRequest) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *GetInputHashRequest) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

type GetInputHashResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	State         GetInputHashResponse_State `protobuf:"varint,1,opt,name=state,proto3,enum=daemon.v1.GetInputHashResponse_State" json:"state,omitempty"`
	Hash          string                     `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInputHashResponse) Reset() {
	*x = GetInputHashResponse{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInputHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInputHashResponse) ProtoMessage() {}

func (x *GetInputHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInputHashResponse.ProtoReflect.Descriptor instead.
func (*GetInputHashResponse) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *GetInputHashResponse) GetState() GetInputHashResponse_State {
	if x != nil {
		return x.State
	}
	return GetInputHashResponse_READY
}

func (x *GetInputHashResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type ExecuteTaskRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskName        string                 `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Command         []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	WorkingDir      string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	TaskEnvironment map[string]string      `protobuf:"bytes,4,rep,name=task_environment,json=taskEnvironment,proto3" json:"task_environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NixEnvironment  []string               `protobuf:"bytes,5,rep,name=nix_environment,json=nixEnvironment,proto3" json:"nix_environment,omitempty"`
	PtyRows         int32                  `protobuf:"varint,6,opt,name=pty_rows,json=ptyRows,proto3" json:"pty_rows,omitempty"`
	PtyCols         int32                  `protobuf:"varint,7,opt,name=pty_cols,json=ptyCols,proto3" json:"pty_cols,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteTaskRequest) Reset() {
	*x = ExecuteTaskRequest{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskRequest) ProtoMessage() {}

func (x *ExecuteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *ExecuteTaskRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *ExecuteTaskRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecuteTaskRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ExecuteTaskRequest) GetTaskEnvironment() map[string]string {
	if x != nil {
		return x.TaskEnvironment
	}
	return nil
}

func (x *ExecuteTaskRequest) GetNixEnvironment() []string {
	if x != nil {
		return x.NixEnvironment
	}
	return nil
}

func (x *ExecuteTaskRequest) GetPtyRows() int32 {
	if x != nil {
		return x.PtyRows
	}
	return 0
}

func (x *ExecuteTaskRequest) GetPtyCols() int32 {
	if x != nil {
		return x.PtyCols
	}
	return 0
}

type ExecuteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskResponse) Reset() {
	*x = ExecuteTaskResponse{}
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskResponse) ProtoMessage() {}

func (x *ExecuteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_daemon_v1_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_daemon_v1_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *ExecuteTaskResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_daemon_v1_daemon_proto protoreflect.FileDescriptor

const file_api_daemon_v1_daemon_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/daemon/v1/daemon.proto\x12\tdaemon.v1\x1a\x17google/rpc/status.proto\"\r\n" +
	"\vPingRequest\"D\n" +
	"\fPingResponse\x124\n" +
	"\x16idle_remaining_seconds\x18\x01 \x01(\x03R\x14idleRemainingSeconds\"\x0f\n" +
	"\rStatusRequest\"\xc7\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12,\n" +
	"\x12last_activity_unix\x18\x04 \x01(\x03R\x10lastActivityUnix\x124\n" +
	"\x16idle_remaining_seconds\x18\x05 \x01(\x03R\x14idleRemainingSeconds\"-\n" +
	"\x0fShutdownRequest\x12\x1a\n" +
	"\bgraceful\x18\x01 \x01(\bR\bgraceful\",\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\vConfigMtime\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12&\n" +
	"\x0fmtime_unix_nano\x18\x02 \x01(\x03R\rmtimeUnixNano\"`\n" +
	"\x0fGetGraphRequest\x12\x10\n" +
	"\x03cwd\x18\x01 \x01(\tR\x03cwd\x12;\n" +
	"\rconfig_mtimes\x18\x02 \x03(\v2\x16.daemon.v1.ConfigMtimeR\fconfigMtimes\"\xd5\x03\n" +
	"\tTaskProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x16\n" +
	"\x06inputs\x18\x03 \x03(\tR\x06inputs\x12\x18\n" +
	"\aoutputs\x18\x04 \x03(\tR\aoutputs\x125\n" +
	"\x05tools\x18\x05 \x03(\v2\x1f.daemon.v1.TaskProto.ToolsEntryR\x05tools\x12\"\n" +
	"\fdependencies\x18\x06 \x03(\tR\fdependencies\x12G\n" +
	"\venvironment\x18\a \x03(\v2%.daemon.v1.TaskProto.EnvironmentEntryR\venvironment\x12\x1f\n" +
	"\vworking_dir\x18\b \x01(\tR\n" +
	"workingDir\x12)\n" +
	"\x10rebuild_strategy\x18\t \x01(\tR\x0frebuildStrategy\x1a8\n" +
	"\n" +
	"ToolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x10GetGraphResponse\x12\x1b\n" +
	"\tcache_hit\x18\x01 \x01(\bR\bcacheHit\x12\x12\n" +
	"\x04root\x18\x02 \x01(\tR\x04root\x12*\n" +
	"\x05tasks\x18\x03 \x03(\v2\x14.daemon.v1.TaskProtoR\x05tasks\"\xab\x01\n" +
	"\x15GetEnvironmentRequest\x12\x15\n" +
	"\x06env_id\x18\x01 \x01(\tR\x05envId\x12A\n" +
	"\x05tools\x18\x02 \x03(\v2+.daemon.v1.GetEnvironmentRequest.ToolsEntryR\x05tools\x1a8\n" +
	"\n" +
	"ToolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x16GetEnvironmentResponse\x12\x1b\n" +
	"\tcache_hit\x18\x01 \x01(\bR\bcacheHit\x12\x19\n" +
	"\benv_vars\x18\x02 \x03(\tR\aenvVars\"\xd9\x01\n" +
	"\x13GetInputHashRequest\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\x12\x12\n" +
	"\x04root\x18\x02 \x01(\tR\x04root\x12Q\n" +
	"\venvironment\x18\x03 \x03(\v2/.daemon.v1.GetInputHashRequest.EnvironmentEntryR\venvironment\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x01\n" +
	"\x14GetInputHashResponse\x12;\n" +
	"\x05state\x18\x01 \x01(\x0e2%.daemon.v1.GetInputHashResponse.StateR\x05state\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\",\n" +
	"\x05State\x12\t\n" +
	"\x05READY\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aUNKNOWN\x10\x02\"\xee\x02\n" +
	"\x12ExecuteTaskRequest\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\x12]\n" +
	"\x10task_environment\x18\x04 \x03(\v22.daemon.v1.ExecuteTaskRequest.TaskEnvironmentEntryR\x0ftaskEnvironment\x12'\n" +
	"\x0fnix_environment\x18\x05 \x03(\tR\x0enixEnvironment\x12\x19\n" +
	"\bpty_rows\x18\x06 \x01(\x05R\aptyRows\x12\x19\n" +
	"\bpty_cols\x18\a \x01(\x05R\aptyCols\x1aB\n" +
	"\x14TaskEnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\x13ExecuteTaskResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\x89\x04\n" +
	"\rDaemonService\x127\n" +
	"\x04Ping\x12\x16.daemon.v1.PingRequest\x1a\x17.daemon.v1.PingResponse\x12=\n" +
	"\x06Status\x12\x18.daemon.v1.StatusRequest\x1a\x19.daemon.v1.StatusResponse\x12C\n" +
	"\bShutdown\x12\x1a.daemon.v1.ShutdownRequest\x1a\x1b.daemon.v1.ShutdownResponse\x12C\n" +
	"\bGetGraph\x12\x1a.daemon.v1.GetGraphRequest\x1a\x1b.daemon.v1.GetGraphResponse\x12U\n" +
	"\x0eGetEnvironment\x12 .daemon.v1.GetEnvironmentRequest\x1a!.daemon.v1.GetEnvironmentResponse\x12O\n" +
	"\fGetInputHash\x12\x1e.daemon.v1.GetInputHashRequest\x1a\x1f.daemon.v1.GetInputHashResponse\x12N\n" +
	"\vExecuteTask\x12\x1d.daemon.v1.ExecuteTaskRequest\x1a\x1e.daemon.v1.ExecuteTaskResponse0\x01B(Z&go.trai.ch/same/api/daemon/v1;daemonv1b\x06proto3"

var (
	file_api_daemon_v1_daemon_proto_rawDescOnce sync.Once
	file_api_daemon_v1_daemon_proto_rawDescData []byte
)

func file_api_daemon_v1_daemon_proto_rawDescGZIP() []byte {
	file_api_daemon_v1_daemon_proto_rawDescOnce.Do(func() {
		file_api_daemon_v1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_daemon_v1_daemon_proto_rawDesc), len(file_api_daemon_v1_daemon_proto_rawDesc)))
	})
	return file_api_daemon_v1_daemon_proto_rawDescData
}

var file_api_daemon_v1_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_daemon_v1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_daemon_v1_daemon_proto_goTypes = []any{
	(GetInputHashResponse_State)(0), // 0: daemon.v1.GetInputHashResponse.State
	(*PingRequest)(nil),             // 1: daemon.v1.PingRequest
	(*PingResponse)(nil),            // 2: daemon.v1.PingResponse
	(*StatusRequest)(nil),           // 3: daemon.v1.StatusRequest
	(*StatusResponse)(nil),          // 4: daemon.v1.StatusResponse
	(*ShutdownRequest)(nil),         // 5: daemon.v1.ShutdownRequest
	(*ShutdownResponse)(nil),        // 6: daemon.v1.ShutdownResponse
	(*ConfigMtime)(nil),             // 7: daemon.v1.ConfigMtime
	(*GetGraphRequest)(nil),         // 8: daemon.v1.GetGraphRequest
	(*TaskProto)(nil),               // 9: daemon.v1.TaskProto
	(*GetGraphResponse)(nil),        // 10: daemon.v1.GetGraphResponse
	(*GetEnvironmentRequest)(nil),   // 11: daemon.v1.GetEnvironmentRequest
	(*GetEnvironmentResponse)(nil),  // 12: daemon.v1.GetEnvironmentResponse
	(*GetInputHashRequest)(nil),     // 13: daemon.v1.GetInputHashRequest
	(*GetInputHashResponse)(nil),    // 14: daemon.v1.GetInputHashResponse
	(*ExecuteTaskRequest)(nil),      // 15: daemon.v1.ExecuteTaskRequest
	(*ExecuteTaskResponse)(nil),     // 16: daemon.v1.ExecuteTaskResponse
	nil,                             // 17: daemon.v1.TaskProto.ToolsEntry
	nil,                             // 18: daemon.v1.TaskProto.EnvironmentEntry
	nil,                             // 19: daemon.v1.GetEnvironmentRequest.ToolsEntry
	nil,                             // 20: daemon.v1.GetInputHashRequest.EnvironmentEntry
	nil,                             // 21: daemon.v1.ExecuteTaskRequest.TaskEnvironmentEntry
}
var file_api_daemon_v1_daemon_proto_depIdxs = []int32{
	7,  // 0: daemon.v1.GetGraphRequest.config_mtimes:type_name -> daemon.v1.ConfigMtime
	17, // 1: daemon.v1.TaskProto.tools:type_name -> daemon.v1.TaskProto.ToolsEntry
	18, // 2: daemon.v1.TaskProto.environment:type_name -> daemon.v1.TaskProto.EnvironmentEntry
	9,  // 3: daemon.v1.GetGraphResponse.tasks:type_name -> daemon.v1.TaskProto
	19, // 4: daemon.v1.GetEnvironmentRequest.tools:type_name -> daemon.v1.GetEnvironmentRequest.ToolsEntry
	20, // 5: daemon.v1.GetInputHashRequest.environment:type_name -> daemon.v1.GetInputHashRequest.EnvironmentEntry
	0,  // 6: daemon.v1.GetInputHashResponse.state:type_name -> daemon.v1.GetInputHashResponse.State
	21, // 7: daemon.v1.ExecuteTaskRequest.task_environment:type_name -> daemon.v1.ExecuteTaskRequest.TaskEnvironmentEntry
	1,  // 8: daemon.v1.DaemonService.Ping:input_type -> daemon.v1.PingRequest
	3,  // 9: daemon.v1.DaemonService.Status:input_type -> daemon.v1.StatusRequest
	5,  // 10: daemon.v1.DaemonService.Shutdown:input_type -> daemon.v1.ShutdownRequest
	8,  // 11: daemon.v1.DaemonService.GetGraph:input_type -> daemon.v1.GetGraphRequest
	11, // 12: daemon.v1.DaemonService.GetEnvironment:input_type -> daemon.v1.GetEnvironmentRequest
	13, // 13: daemon.v1.DaemonService.GetInputHash:input_type -> daemon.v1.GetInputHashRequest
	15, // 14: daemon.v1.DaemonService.ExecuteTask:input_type -> daemon.v1.ExecuteTaskRequest
	2,  // 15: daemon.v1.DaemonService.Ping:output_type -> daemon.v1.PingResponse
	4,  // 16: daemon.v1.DaemonService.Status:output_type -> daemon.v1.StatusResponse
	6,  // 17: daemon.v1.DaemonService.Shutdown:output_type -> daemon.v1.ShutdownResponse
	10, // 18: daemon.v1.DaemonService.GetGraph:output_type -> daemon.v1.GetGraphResponse
	12, // 19: daemon.v1.DaemonService.GetEnvironment:output_type -> daemon.v1.GetEnvironmentResponse
	14, // 20: daemon.v1.DaemonService.GetInputHash:output_type -> daemon.v1.GetInputHashResponse
	16, // 21: daemon.v1.DaemonService.ExecuteTask:output_type -> daemon.v1.ExecuteTaskResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_daemon_v1_daemon_proto_init() }
func file_api_daemon_v1_daemon_proto_init() {
	if File_api_daemon_v1_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_daemon_v1_daemon_proto_rawDesc), len(file_api_daemon_v1_daemon_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_daemon_v1_daemon_proto_goTypes,
		DependencyIndexes: file_api_daemon_v1_daemon_proto_depIdxs,
		EnumInfos:         file_api_daemon_v1_daemon_proto_enumTypes,
		MessageInfos:      file_api_daemon_v1_daemon_proto_msgTypes,
	}.Build()
	File_api_daemon_v1_daemon_proto = out.File
	file_api_daemon_v1_daemon_proto_goTypes = nil
	file_api_daemon_v1_daemon_proto_depIdxs = nil
}
