// Code generated by kessoku. DO NOT EDIT.

package app

import (
	"github.com/mazrean/kessoku"
	"go.trai.ch/bob/internal/adapters/cas"
	"go.trai.ch/bob/internal/adapters/config"
	"go.trai.ch/bob/internal/adapters/fs"
	"go.trai.ch/bob/internal/adapters/logger"
	"go.trai.ch/bob/internal/adapters/shell"
	"go.trai.ch/bob/internal/core/ports"
	"go.trai.ch/bob/internal/engine/scheduler"
)

func InitializeApp() (*Components, error) {
	logger0 := kessoku.Provide(logger.New).Fn()()
	var err error
	store, err := kessoku.Bind[ports.BuildInfoStore](kessoku.Provide(cas.NewStore)).Fn()()
	if err != nil {
		var zero *Components
		return zero, err
	}
	resolver := kessoku.Bind[ports.InputResolver](kessoku.Provide(fs.NewResolver)).Fn()()
	walker := kessoku.Provide(fs.NewWalker).Fn()()
	loader := kessoku.Bind[ports.ConfigLoader](kessoku.Provide(config.NewLoader)).Fn()(logger0)
	executor := kessoku.Bind[ports.Executor](kessoku.Provide(shell.NewExecutor)).Fn()(logger0)
	hasher := kessoku.Bind[ports.Hasher](kessoku.Provide(fs.NewHasher)).Fn()(walker)
	scheduler0 := kessoku.Provide(scheduler.NewScheduler).Fn()(executor, store, hasher, resolver, logger0)
	app := kessoku.Provide(New).Fn()(loader, scheduler0)
	components := kessoku.Provide(NewComponents).Fn()(app, logger0, loader)
	return components, nil
}
