name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

env:
  CARGO_TERM_COLOR: always

jobs:
  proto:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: bufbuild/buf-action@v1
        with:
          lint: true
          format: true
          breaking: true
          push: false
          pr_comment: true
  rust:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true
          toolchain: stable
          components: rustfmt, clippy

      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true

      - name: Check Formatting
        run: cargo fmt --check

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

      - name: Clippy
        run: cargo clippy -- -D warnings
  nix:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Flake Metadata
        run: nix flake check

      - name: Verify rust DevShell
        run: nix develop --command cargo version

      - name: Verify buf DevShell
        run: nix develop --command buf --version

      - name: Nix Format Check
        run: nix fmt -- --check .
